# Generated by Django 3.2.2 on 2021-05-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='checkList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklistitem_set', to='core.checklist'),
        ),
    ]
